export const researchFields = [
  "Archaeology",
  "Ethnology and Cultural Anthropology",
  "Philosophy",
  "History",
  "Linguistics",
  "Literary Studies",
  "Culture and Religion Studies",
  "Arts Studies",
  "Polish Studies",
  "Architecture and Urban Planning",
  "Automation, Electronics, Electrical Engineering and Space Technologies",
  "Information and Communication Technology",
  "Safety Engineering",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Geodesy and Transport",
  "Materials Engineering",
  "Mechanical Engineering",
  "Environmental Engineering",
  "Mining and Energy",
  "Heritage Protection and Conservation of Monuments",
  "Medical Biology",
  "Pharmacology and Pharmacy",
  "Medical Sciences",
  "Physical Culture Science",
  "Health Sciences",
  "Family Studies",
  "Forestry",
  "Agriculture and Horticulture",
  "Food and Nutrition Technology",
  "Animal Science and Fisheries",
  "Economics and Finance",
  "Socio-Economic Geography and Spatial Management",
  "Security Studies",
  "Social Communication and Media Studies",
  "Political and Administrative Sciences",
  "Management and Quality Studies",
  "Law",
  "Sociology",
  "Educational Sciences",
  "Canon Law",
  "Psychology",
  "International Relations",
  "Astronomy",
  "Biotechnology",
  "Computer and Information Sciences",
  "Mathematics",
  "Biological Sciences",
  "Chemical Sciences",
  "Physical Sciences",
  "Earth and Related Environmental Sciences",
  "Biblical Studies",
  "Theology",
  "Veterinary Science",
  "Film and Theatre",
  "Music",
  "Fine Arts and Art Conservation"
]

export const operatingFieldsOfCompany = [
  "Artificial intelligence (AI)",
  "Material sciences",
  "Digital",
  "Electronics",
  "Robotics",
  "Finance",
  "Food industry",
  "Health",
  "Mobility",
  "Environment",
  "Energy",
  "Human resources",
  "Manufacturing",
  "Sports"
]

export const companyDevelopmentLevels = [
  "Pree-seed",
  "Seed",
  "Early stage (series A)",
  "Growth stage (series B)",
  "Expansion stage (series C)",
  "Exit stage"
]

export const investmentLevels = [
  "0-100 000 Euro",
  "100 001-500 000 Euro",
  "500 001-1 000 000 Euro",
  "1 000 001-2 000 000 Euro",
  "2 000 001-5 000 000 Euro",
  "Over 5 000 000 Euro"
]
